version: '3.9'
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
  web:
    build:
      context: ./fastapi-server
    hostname: web
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      rabbit:
        condition: service_healthy
    links:
      - rabbit
#  worker:
#    build:
#      context: ./cloud-worker
#    deploy:
#      replicas: 1
#    links:
#      - rabbit
#    depends_on:
#      rabbit:
#        condition: service_healthy