RABBITMQ_RESULT_QUEUE_NAME = 'result_queue'
RABBITMQ_JOB_QUEUE_NAME    = 'job_queue'
# RABBITMQ_CONNECTION_URL    = 'amqp://guest:guest@localhost'
RABBITMQ_CONNECTION_URL    = 'amqp://guest:guest@172.31.48.1'
# RABBITMQ_CONNECTION_URL    = 'amqp://guest:guest@rabbit'